Write parsers
BuTaMuH4er/moto pull request #1
Opened 2021-03-04 06:23 UTC by BuTaMuH4er

Вопрос по take_data_cyclechaos
Сейчас есть характеристики мотоциклов на вывод, выводит название + список свойств формата: ['Название ТТХ', 'ТТХ'].
Вопрос, стоит ли это переводить в Json для удобства или сразу парсить для передачи в БД?

2021-03-05 11:35 UTC, alexandrettio commented
Я бы не стала руками переводить в json и доверила бы это сериализатору который в будущем появится. Пока я считаю стоит заносить эти свойства в БД.
Список полей стоит ограничить теми что ты умеешь вынимать с сайта (в последствии можно будет расширить)

2021-03-05 12:09 UTC, alexandrettio requested changes

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +    headers = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0'}
Сейчас передача хедеров происходит в каждом запросе. и везде они одинаковые. Такое лучше выносить либо в константу, либо в отдельную константу, либо иногда удобен вариант с отдельной функцией которая всегда возвращает хедеры

Сейчас проблема в том что тебе может потребоваться поменять хедеры во всех местах...

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +    main_url = 'http://www.bikerwiki.ru'
Аналогично с хедерами

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +        open(f'pages_biker_wiki/{file_name}.html', 'wb').write(html.content)
Так лучше не делать. В файл всегда пишем с помощью менеджера контекста (`with open...`)
Иначе в процессе работы программы что-то пойдет не так и файл "никогда" не закроется. На проде такие ситуации приводят к ощутимым проблемам

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +        return e
По ощущениям, следует залогировать ошибку, а не просто её возвращать дальше и печатать на экран

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +    with ThreadPoolExecutor(max_workers=10) as executor:
Аналогичный код повторяется ниже, лучше его вынести в функцию

2021-03-05 12:09 UTC, alexandrettio commented on parser/bike_wiki_pars.py
> +            count += 1
Я предлагаю переписать 
threads.append(...) на 
threads.extend(...)

и соответсвенно в скобках написать генератор executer'ов
[executor.submit(download_file, url, file_name) 2 for ... in ...]

Тогда можно избавиться от счетчика для sleep

2021-03-05 12:09 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +def export_to_json(data_input):
Лучше заменить грязную функцию на чистую. Чистые функции не меняют внешний мир в том числе с помощью print. Вместо этого они собирают всю информацию и возвращают её с помощью return.
Это позволяет их запускать безопасно сколько угодно раз.
Грязных функций должно быть в коде по минимуму

2021-03-09 15:34 UTC, alexandrettio requested changes

2021-03-09 15:34 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +            if x[0] == 'Manufacturer':
А если x[0] != 'Manufacturer'? Что  окажется в brand_name/model...?

2021-03-09 15:34 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +    except UnboundLocalError:
Вот именно это исключение так обрабатывать не стоит. Иначе ты исправишь потом функцию и исправишь с ошибкой, вместо того чтоб ошибку заметить, проигнорируешь её.
Это прям критично

2021-03-09 15:34 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +                brand_name = y[0]
Эти 4 строчки повторяются -- стоит вынести в функцию

2021-03-09 20:07 UTC, BuTaMuH4er commented on parser/take_data_cyclechaos.py
> +            if x[0] == 'Manufacturer':
То там будет любая другая строка с названием технических характеристик, например 'engine'.

2021-03-09 20:09 UTC, BuTaMuH4er commented on parser/take_data_cyclechaos.py
> +    except UnboundLocalError:
В данном случае обрабатываются 2 типа страниц, в одной из страниц таблица имеет другую разметку, я так дополнительно с помощью второй функции могу спарсить еще 240 страниц.

2021-03-10 07:23 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +    except UnboundLocalError:
Unbound local error это ошибка про то что ты пытаешься использовать переменную которую не определил. Это очень опасная ошибка. Установи изначально эти переменные в None и проверяй появилось ли в них значение если это почему-то важно.
Так как сейчас в коде можно пропустить новые ошибки, когда будешь править код

2021-03-10 07:24 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +            if x[0] == 'Manufacturer':
И в этом случае переменные будут неопределены, а это опасно

2021-03-10 19:59 UTC, BuTaMuH4er commented on parser/take_data_cyclechaos.py
> +    except UnboundLocalError:
тогда можно просто написать через if a,b,c,: return a,b,c? Тогда не понимаю как проверять страницы с другой разметкой, потому что останутся еще страницы в которых просто нету данных, как вариант вижу if + elif.

2021-03-11 06:15 UTC, alexandrettio requested changes

2021-03-11 06:15 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +    except UnboundLocalError:
Лучше добавить одну переменную флаг условно "unable_to_parse_as_chart" и возвращать его тоже. Если он true запускать другой вид парсинга. Если и он не дал данные либо иметь ещё один парсинг либо игнорировать страницу

2021-03-12 08:27 UTC, alexandrettio requested changes

2021-03-12 08:27 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +    db_session.add(motocycle)
вот тут хочется посмотреть как к этому моменту выглядит motocyle, что в него записано

2021-03-12 08:27 UTC, alexandrettio commented on parser/take_data_cyclechaos.py
> +    db_session.commit()
Обычно коммит делается не на каждое добавление а порциями, тк потенциально это долгое место. возможно стоит в отдельном месте собрать список объектов класса мотоцикл, а потом из всех добавить и закоммитить только 1 раз

2021-03-13 08:28 UTC, alexandrettio approved these changes

2021-03-13 10:12 UTC, merged