Create api
BuTaMuH4er/moto pull request #2
Opened 2021-03-16 21:19 UTC by BuTaMuH4er

Не выводит правильно страницу в HTML

2021-03-16 21:22 UTC, alexandrettio approved these changes

2021-03-19 05:55 UTC, alexandrettio requested changes

2021-03-19 05:55 UTC, alexandrettio commented on api/views.py
> +class ProductAPI(Resource):
А почему оно ProductAPI?

2021-03-19 05:55 UTC, alexandrettio commented on api/views.py
> +        dict_cycles = []
В названии стараемся не указывать типы данных. Тем более внешний объект у тебя список. лучше что-то вроде serialized_motoscycles

или вообще обойтись без переменной
return [moto.to_dict() for moto in motocycles] (лучше результат запроса к бд все таки назвать вомножественном числе)

2021-03-19 08:56 UTC, BuTaMuH4er commented on api/views.py
> +class ProductAPI(Resource):
Исправлю, не подумал когда создавал.

2021-03-19 09:07 UTC, alexandrettio approved these changes

2021-03-23 14:38 UTC, merged