Make reqparse
BuTaMuH4er/moto pull request #4
Opened 2021-04-01 14:33 UTC by BuTaMuH4er

2021-04-03 07:14 UTC, alexandrettio requested changes

2021-04-03 07:14 UTC, alexandrettio commented on api/test_query.py
> +    if isinstance(id, int):
Это бесполезная проверка. У тебя в api.add_resource указано что id только int. 
Что сейчас происходит если вызываешь эту функцию со строкой?

2021-04-03 07:14 UTC, alexandrettio commented on api/test_query.py
> +        if count_vehicles:
Не очень оптимальная последовательность. Получается ты делаешь два запроса в базу вместо одного. Один из них эффективный по трафику, который передается, второй медленный и загружающий канал передачи данных. Но на самом деле тебе бы хватило только второго запроса. Получив все записи мы можем сказать сколько их

+ в таком случае лучше не count а exists. так как exists отработает быстрее, а суть запроса сохранится

2021-04-03 07:14 UTC, alexandrettio commented on api/test_query.py
> +        count_vehicles = Motocycle.query.filter_by(id=id).count()
лучше не filter_by(id=id), а get(id). Возможно sqlalchemy как-то оптимизирует такой фильтр, но получение через get абсолютно точно работает за логарифмическое время

2021-04-03 07:47 UTC, BuTaMuH4er commented on api/test_query.py
> +    if isinstance(id, int):
Отрабатывает в любом случае. Я уже это заметил, когда проверял работу исключений.

2021-04-03 07:50 UTC, BuTaMuH4er commented on api/test_query.py
> +        if count_vehicles:
Я в таком случае могу 1 условие убрать?

2021-04-03 08:08 UTC, alexandrettio commented on api/test_query.py
> +        if count_vehicles:
Да.
Я бы в целом заменила на get или  даже get_or_404

2021-04-06 07:36 UTC, alexandrettio approved these changes

2021-04-15 07:20 UTC, merged